Feat inbox
dev-3-2019-1/SGRA-Backend pull request #12
Opened 2019-05-24 23:50 UTC by isaqueha

This PR adds the Inbox screen.

This screen filters and shows all the messages where the Logged User is a `receiver`.

Story: https://trello.com/c/rpMmeeFu

2019-05-26 23:28 UTC, nathanss requested changes
I don't understand, I think there's some issue with the back-end logic.

When I send a new message, it goes back to the message list normally. But if I go to another part of the application and then return, all the messages disappear.

I think it would be a good idea to implement authentication now. There is user story 12 regarding that. Couldn't this be implemented along with user story 12?

2019-05-30 02:35 UTC, isaqueha commented
Hey @nathanss 

I could not reproduce the issue you've mentioned. Can you please provide some further details on how to reproduce this?

And about authentication, I would rather develop it in a new PR, just to keep things better separated. Also, I'm afraid I wouldn't be able to develop the authentication now, I'm a bit out of time for it.

Any issues regarding the code itself?

2019-05-30 02:55 UTC, nathanss commented
I'll approve it and we can handle anything that shows up as a bug eventually.

2019-05-30 02:56 UTC, nathanss approved these changes

2019-05-30 02:56 UTC, merged