CRUD Messages
dev-3-2019-1/SGRA-Backend pull request #4
Opened 2019-04-21 00:33 UTC by isaqueha

This PR adds the CRUD for Messages.

Link: https://trello.com/c/kfp5Fopn

⚠️ **WARNING** ⚠️ 
Please merge this after [this PR #3](https://github.com/dev-3-2019-1/SGRA-Backend/pull/3)

2019-04-21 02:18 UTC, nathanss requested changes
As Jorge said in the user story #4: 
"Esta story é referente apenas à criação do Modelo da Mensagem. Não é necessário uma tela de cadastro de mensagem, pois será tratada na Story #5."

I think we need to discuss how we are going to handle this. I researched and MongoDB offers [Schema Validations](https://docs.mongodb.com/manual/core/schema-validation/). We could develop one validation for our messagecollection. The next question is, if we develop this validation, how are we going to share it, as we all run the database in our machines separately.

2019-04-21 02:26 UTC, isaqueha commented
I know the Message Creation screen was not needed for this Story, but the effort for it was minimal.
Also, I thought it would make sense to let this screen for now, so we can test this feature.

@nathanss What if we keep the validations for a next story?
Also, do you think we should delete the Create User screen?

2019-04-22 03:40 UTC, nathanss commented
I will approve everything, the "CRUD messages" screen can become an "sysadmin with all permissions" thing later.

Also, as I said in whatsapp: 
"encontrei um bug com todos nossos selects no projeto. A gente estava informando "select = true" ou "select = false", quando na verdade os atributos booleanos não funcionam dessa forma, se você coloca "select" ele vai como true, se não coloca nada, é false."
This is fixed in commit c2e4c55.

2019-04-22 03:40 UTC, nathanss approved these changes

2019-04-22 03:40 UTC, merged